# Generated by Django 3.1.2 on 2020-10-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('zip', models.CharField(blank=True, max_length=6)),
                ('website', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('price_level', models.CharField(blank=True, choices=[('cheap', '$'), ('moderate', '$$'), ('average', '$$$'), ('expensive', '$$$$')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_restaurant_category', to='categories.category')),
            ],
        ),
    ]
