# Generated by Django 3.1.2 on 2020-10-26 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=30)),
                ('author', models.ManyToManyField(blank=True, related_name='m2m_interest_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
